# Generated by Django 5.2.15 on 2026-06-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birthdate', models.CharField(blank=True, max_length=10)),
                ('street', models.CharField(blank=True, max_length=300)),
                ('neighborhood', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=9)),
                ('monthly_income', models.FloatField(default=0)),
                ('password_hash', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('pensao_alimenticia', 'Pensão Alimentícia'), ('aluguel', 'Aluguel'), ('servicos_essenciais', 'Luz / Água / Gás'), ('financiamento_garantia', 'Financiamento (carro/imóvel)'), ('emprestimo_bancario', 'Empréstimo Bancário'), ('cartao_credito', 'Cartão de Crédito'), ('loja_comercio', 'Loja / Comércio'), ('outros', 'Outros')], default='outros', max_length=50)),
                ('total_amount', models.FloatField()),
                ('monthly_payment', models.FloatField(default=0)),
                ('due_date', models.CharField(blank=True, max_length=10, null=True)),
                ('debt_status', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='debtfree.userprofile')),
            ],
            options={
                'db_table': 'debt',
                'ordering': ['created_at'],
            },
        ),
    ]
